[workspace]
resolver = "2"
members = [
    "cli",
    "vm",
    "circuits",
]

[patch.crates-io]
plonky2_field =  { git = "https://github.com/mir-protocol/plonky2.git" }
plonky2_maybe_rayon =  { git = "https://github.com/mir-protocol/plonky2.git" }
plonky2 = { git = "https://github.com/mir-protocol/plonky2.git" }
starky = { git = "https://github.com/0xmozak/plonky2.git" }
plonky2_util =  { git = "https://github.com/mir-protocol/plonky2.git" }
