[workspace]
members = ["cli", "vm", "circuits"]
resolver = "2"

[profile.test]
# Full list of settings: https://doc.rust-lang.org/cargo/reference/profiles.html#release
inherits = "release"
# We are running our tests in release mode to make them faster.
# But we want to catch overflow errors, so we enable overflow checks here for now:
overflow-checks = true
# This is false by default in the 'release' profile but we want
# better re-compilation times here
incremental = true

[patch.crates-io]
plonky2 = { git = "https://github.com/0xmozak/plonky2.git" }
plonky2_field = { git = "https://github.com/0xmozak/plonky2.git" }
plonky2_maybe_rayon = { git = "https://github.com/0xmozak/plonky2.git" }
plonky2_util = { git = "https://github.com/0xmozak/plonky2.git" }
starky = { version = "0.1.2", git = "https://github.com/dimdumon/plonky2-mozak.git", branch = "roman/debug-version-of-c-consumer", commit = "a0e6aa61bc5207594288fec15304c760417423c6" }
