[package]
name = "mozak-vm"
description = "RISC V ISA based knowledge argument VM"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", default-features = false }
elf = { version = "0.7" }

[dev-dependencies]
test-case = "3.1.0"

[features]
default = ["std"]
std = ["anyhow/std"]
