[unstable]
build-std = ["alloc", "core", "compiler_builtins", "std", "panic_abort", "proc_macro"]
build-std-features = ["compiler-builtins-mem"]

[build]
# NOTE: to debug memory map, add this: "-Clink-arg=-Map=linker.map" to the rustflags, linker.map will be in parent directory
#       can't find a right way to reference target-dir from linker arguments
rustflags = ["-C", "passes=loweratomic", "-Zlocation-detail=none","-Clink-arg=-T./.cargo/riscv32im-mozak-zkvm.ld", "-Clink-arg=-Map=linker.map"]
target = "./.cargo/riscv32im-mozak-zkvm-elf.json"

[target.riscv32im-mozak-zkvm-elf]
runner = "../target/release/mozak-cli -vvv run"
