[workspace]
[package]
edition = "2021"
name = "inputtape-mozakvm"
version = "0.1.0"

[dependencies]
inputtape-core-logic = { path = "../core-logic" }
mozak-sdk = { path = "../../../sdk" }
rkyv = { version = "=0.8.0-alpha.1", default-features = false, features = ["pointer_width_32", "alloc", "bytecheck"] }
rkyv_derive = "=0.8.0-alpha.1"

[features]
std = []

# The following is read by `run_examples.py`
[package.metadata.mozak]
example_program_id = "MZK-5de9bc1bb4cb7a9f9cf991a32230d014b44274ea5464a352f089a8cccc486915"
