[package]
categories = ["cryptography"]
description = "MozakVM cli"
edition = "2021"
keywords = ["crypto", "zero-knowledge", "vm"]
license = "All rights reserved"
name = "mozak-cli"
readme = "README.md"
repository = "https://github.com/0xmozak/mozak-vm"
version = "0.1.0"

[dependencies]
clap = { version = "4.5", features = [
  "derive",
  "cargo",
  "env",
  "unicode",
  "wrap_help",
] }
mozak-circuits = { path = "../circuits", features = ["test", "enable_poseidon_starks"] }
mozak-runner = { path = "../runner", features = ["test"] }
mozak-sdk = { path = "../sdk", features = ["std"] }
# TODO(Matthias): implement shell completion for CLI via clap_complete
# clap_complete = "4.3"
anyhow = "1.0"
clap-verbosity-flag = "2.2"
clap_derive = "4.5"
clio = { version = "0.3", features = ["clap-parse"] }
env_logger = "0.11"
itertools = "0.12"
log = "0.4"
# plonky2 = { version = "0", features=["parallel"] }
# ["gate_testing", "parallel", "rand_chacha", "std", "timing"]
# No parallel:
plonky2 = { version = "0", default-features = false, features=["gate_testing", "rand_chacha", "std", "timing"] }
rkyv = { version = "0.8.0-alpha.2", default-features = false, features = ["pointer_width_32", "alloc"] }
serde_json = "1.0"
# default = ["parallel", "std", "timing"]
# No parallel:
starky = { version = "0", default-features = false, features = ["std", "timing"] }
tempfile = "3"

[dev-dependencies]
mozak-circuits = { path = "../circuits", features = ["test"] }
mozak-runner = { path = "../runner", features = ["test"] }
proptest = "1.4"
