# Keeping this for legacy purpose
# [unstable]
# build-std = ["alloc", "core", "compiler_builtins", "std", "panic_abort", "proc_macro"]
# build-std-features = ["compiler-builtins-mem"]

# [build]
# rustflags = ["-C", "passes=loweratomic", "-Zlocation-detail=none"]
# target = "./.cargo/riscv32im-mozak-mozakvm-elf.json"

[alias]
build-mozakvm = """
    build --release \
          --target riscv32im-mozak-mozakvm-elf \
          -Zbuild-std=alloc,core,compiler_builtins,std,panic_abort,proc_macro \
          -Zbuild-std-features=compiler-builtins-mem
    """
run-mozakvm = """
    run --release \
          --target riscv32im-mozak-mozakvm-elf \
          -Zbuild-std=alloc,core,compiler_builtins,std,panic_abort,proc_macro \
          -Zbuild-std-features=compiler-builtins-mem 
    """
clippy-mozakvm = """
    clippy --locked --all-features \
        --target riscv32im-mozak-mozakvm-elf \
        -Zbuild-std=alloc,core,compiler_builtins,std,panic_abort,proc_macro \
        -Zbuild-std-features=compiler-builtins-mem  
        -- \
        -D warnings  
"""
[target.riscv32im-mozak-mozakvm-elf]
runner = "examples/scripts/run_script.sh"
rustflags = ["-C", "passes=loweratomic", "-Zlocation-detail=none", "-Clink-arg=-T../.cargo/riscv32im-mozak-mozakvm.ld"]

[env]
# path where riscv32im-mozak-mozakvm-elf.json lies
RUST_TARGET_PATH = { value = ".cargo/", relative = true,  force = true }
