[workspace]
members = [
  # Members that depend only on sdk::core
  "bss-tester",
  "fibonacci",
  "min-max",
  "memory-access",
  "panic",
  "static-mem-access",
  "sha2",
  "rkyv-serialization",
  "empty",

  # Members that depend on more than sdk::core
  "token",
  "wallet",
  "inputtape",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"

[patch.crates-io]
plonky2 = { git = "https://github.com/0xmozak/plonky2.git" }
plonky2_maybe_rayon = { git = "https://github.com/0xmozak/plonky2.git" }
# We need to nail down the exact dependencies, to avoid upgrading to 0.8.0-alpha.2, which has an incompatible API.
rkyv = { git = "https://github.com/rkyv/rkyv.git", rev = "626cb2121b8910feb9402589a21bfe0e4a78b98d" }
rkyv_derive = { git = "https://github.com/rkyv/rkyv.git", rev = "626cb2121b8910feb9402589a21bfe0e4a78b98d" }
