[package]
edition = "2021"
name = "inputtape-native"
version = "0.1.0"

[build-dependencies]
build-scripts = { path = "../../../build-scripts"}

[dependencies]
inputtape-core-logic = { path = "../core-logic" }
mozak-sdk = { path = "../../../sdk" }
