[package]
name = "node"
version = "0.1.0"
edition = "2021"
type = "lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = { version = "0.8.5", optional = true }

[features]
default = ["dummy-server"]
test-features = ["dummy-server"]

dummy-server = ["rand"]
