[package]
name = "node"
version = "0.1.0"
edition = "2021"
type = "lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

thiserror = "1.0.48"
rand = { version = "0.8.5", optional = true }
sha3 = "0.10.8"

[features]
default = ["dummy-system"]
test-features = ["dummy-system"]

dummy-system = ["rand"]
