[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
flexbuffers = "2.0.0"
thiserror = "1.0.48"
rand = { version = "0.8.5", optional = true }
sha3 = "0.10.8"

mozak-runner = { git = "ssh://git@github.com/0xmozak/mozak-vm.git", branch = "main", features = ["serialize", "test"] }
mozak-circuits = { git = "ssh://git@github.com/0xmozak/mozak-vm.git", branch = "main", features = ["test"] }
plonky2 = { git = "https://github.com/0xmozak/plonky2.git" }

[features]
default = ["dummy-system"]
test-features = ["dummy-system"]

dummy-system = ["rand"]
