[unstable]
build-std = [
  "alloc",
  "core",
  "compiler_builtins",
  "panic_abort",
  "proc_macro",
  "std",
]
build-std-features = ["compiler-builtins-mem"]

[build]
rustflags = ["-C", "passes=loweratomic"]
target = "./.cargo/riscv32im-mozak-zkvm-elf.json"

[target.riscv32im-mozak-zkvm-elf]
runner = "../target/release/mozak-cli -vvv run"
