name: Install rust toolchain

inputs:
  rust-version:
    required: false
    default: nightly-2023-06-17
    type: string
  cache-key:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust-version }}
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.cache-key != '' }}
      with:
        prefix-key: ${{ inputs.cache-key }}
    
    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.cache-key == '' }}
