name: Install rust toolchain

inputs:
  cache-key:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Get rust version (via python3)
      run: python3 -c "
import sys
for line in sys.stdin:
    line = line.strip()
    # Assumed the input to be of form {  channel = "nightly-2023-08-01"  }
    if line.startswith('channel ='):
        ver = line.split('=')[1].strip().strip('\"')
        print(f'RUST_VERSION={ver}')
" < rust-toolchain.toml >> $GITHUB_ENV
      shell: bash

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.RUST_VERSION }}
        components: rustfmt, clippy

    - name: Install nextest
      uses: taiki-e/install-action@nextest

    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.cache-key != '' }}
      with:
        prefix-key: ${{ inputs.cache-key }}

    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.cache-key == '' }}