name: Install rust toolchain

inputs:
  cache-key:
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Get rust version (via python3)
      run: |
        cat rust-toolchain.toml | perl -e "
        use feature 'say';
        my \$file_contents = do { local \$/; <STDIN> };
        while (\$file_contents =~ /channel = \"(.*)\"/g) {
            my \$match = \$1;
            say \"RUST_VERSION=\\\"\$match\\\"\";
        }" >> $GITHUB_ENV
      shell: bash

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.RUST_VERSION }}
        components: rustfmt, clippy

    - name: Install nextest
      uses: taiki-e/install-action@nextest

    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.cache-key != '' }}
      with:
        prefix-key: ${{ inputs.cache-key }}

    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.cache-key == '' }}
