name: Install rust toolchain

inputs:
  cache-key:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Get rust version
      shell: python3 {0}
      run: |
        import os
        import tomllib

        with open(os.environ["GITHUB_ENV"], "at") as github_env, open(
            "rust-toolchain.toml", "rb"
        ) as rust_toolchain:
            github_env.write(
                f'RUST_VERSION="{tomllib.load(rust_toolchain)["toolchain"]["channel"]}"\n'
            )
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.RUST_VERSION }}
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.cache-key != '' }}
      with:
        prefix-key: ${{ inputs.cache-key }}
    
    - uses: Swatinem/rust-cache@v2
      if: ${{ inputs.cache-key == '' }}
