[package]
edition = "2021"
name = "fibonacci-mozak-guest"
version = "0.1.0"

[dependencies]
guest = { path = "../../guest" }

[[bin]]
name = "fibonacci"
path = "main.rs"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
