[package]
name = "mozak-node-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = { version = "2.0.0", features = ["rand_core"] }
derive_more = "0.99.17"
im = { version = "15.1.0" }
rand = "0.8.5"
sha3 = "0.10.8"

serde = { version = "1.0.189", features = [
  "derive",
  "alloc",
], default-features = false }
