# This package assumes `mozak` compilation target
[package]
edition = "2021"
name = "mozak-sdk"
version = "0.1.0"

categories = ["cryptography", "sdk"]
description = "Mozak protocol sdk"
keywords = ["crypto", "zero-knowledge", "sdk"]
license = "All rights reserved"
readme = "README.md"
repository = "https://github.com/0xmozak/mozak-node"

[dependencies]
