[package]
categories = ["development-tools", "zk"]
description = "Provides tools for writing programs for mozak platform"
edition = "2021"
keywords = ["sdk"]
license = "Apache-2.0"
name = "mozak-sdk"
readme = "README.md"
repository = "https://github.com/0xmozak/mozak-node/sdk"
version = "0.1.0"

[dependencies]
mozak-system = { path = "../system", features = ["mozak-ro-memory"] }
rkyv = { version = "0.7.1", default-features = false, features = ["size_32", "alloc"] }
once_cell = { version = "1.19.0", default-features = false, features = ["race"] }
# lazy_static = { version = "1.4.0", default-features = false, features = ["spin_no_std"] }

[target.'cfg(not(target_os="zkvm"))'.dependencies.lazy_static]
version = "1.4.0"

[target.'cfg(not(target_os="zkvm"))'.dependencies.hex]
version = "0.4"

[target.'cfg(not(target_os="zkvm"))'.dependencies.serde]
features = ["derive"]
version = "1.0"
