[package]
categories = ["cryptography"]
description = "MozakVM circuits"
edition = "2021"
keywords = ["crypto", "zero-knowledge", "vm"]
license = "All rights reserved"
name = "mozak-circuits"
readme = "README.md"
repository = "https://github.com/0xmozak/mozak-vm"
version = "0.1.0"

[dependencies]
anyhow = { version = "1.0", default-features = false }
bitfield = "0.14.0"
flexbuffers = "2.0.0"
itertools = "0.11.0"
lazy_static = "1.4.0"
log = "0.4.19"
mozak-vm = { path = "../vm" }
plonky2 = "0.1.3"
plonky2_maybe_rayon = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
starky = { version = "0.1.2", git = "https://github.com/dimdumon/plonky2-mozak.git", branch = "roman/debug-version-of-c-consumer", commit = "a0e6aa61bc5207594288fec15304c760417423c6" }
thiserror = "1.0.44"

[dev-dependencies]
env_logger = { version = "0.10.0" }
mozak-vm = { path = "../vm", features = ["test"] }
proptest = "1.2.0"

[features]
test = []
