[package]
name = "circuits3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mozak-circuits = { path = "../circuits"}
p3-field = { git = "https://github.com/0xmozak/plonky3.git"}     
p3-matrix = { git = "https://github.com/0xmozak/plonky3.git"}   
p3-air = { git = "https://github.com/0xmozak/plonky3.git"}   


[dev-dependencies]
rand = "0.8.5"
p3-goldilocks = { git = "https://github.com/0xmozak/plonky3.git"}   
p3-fri = { git = "https://github.com/0xmozak/plonky3.git"}   
p3-keccak = { git = "https://github.com/0xmozak/plonky3.git"}   
p3-ldt = { git = "https://github.com/0xmozak/plonky3.git"}   
p3-mds = { git = "https://github.com/0xmozak/plonky3.git"}   
p3-merkle-tree = { git = "https://github.com/0xmozak/plonky3.git"}   
p3-poseidon2 = { git = "https://github.com/0xmozak/plonky3.git"}   
p3-symmetric = { git = "https://github.com/0xmozak/plonky3.git"}   
p3-uni-stark = { git = "https://github.com/0xmozak/plonky3.git"} 
p3-challenger = { git = "https://github.com/0xmozak/plonky3.git"}   
p3-commit = { git = "https://github.com/0xmozak/plonky3.git"}   
p3-dft = { git = "https://github.com/0xmozak/plonky3.git"}   
