name: CI

on:
  push:
    branches: [ "main" ]
  pull_request: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolkit
        uses: ./.github/actions/rust

      - name: Give GitHub Actions access to mozak-vm 
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.MOZAK_VM_DEPLOY_KEY }}

      - name: Run tests
        run: cargo nextest run --locked --all-targets

  cargo-clippy:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolkit
        uses: ./.github/actions/rust

      - name: Give GitHub Actions access to mozak-vm 
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.MOZAK_VM_DEPLOY_KEY }}

      - name: Run Clippy linter
        run: cargo clippy --all-features --all-targets -- -D warnings

  cargo-fmt:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolkit
        uses: ./.github/actions/rust

      - name: Run fmt
        run: cargo fmt --all --check

  taplo-fmt:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolkit
        uses: ./.github/actions/rust

      - name: Install taplo
        run: cargo install taplo-cli --locked

      - name: taplo fmt
        run: taplo fmt --check
