name: Run tests on MacOS

on:
  push:
    branches:
      - release/*
    tags:
      - "*"

  # Triggers the workflow every sunday
  schedule:
    - cron: "0 18 * * 0"

env:
  CARGO_TERM_COLOR: always
  NIGHTLY_RUST_VERSION: nightly-2023-06-17

jobs:
  cargo-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.NIGHTLY_RUST_VERSION }}

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --locked --all-targets
